version: "3.1"

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  nodejs-app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - HOST=mongodb
    # volumes:
    #   - "./:/usr/src/app"
